### ISSUE TITLE
error - roslaunch room_evac_gazebo room_evac.launch

### ISSUE THREAD

**Issue by noblespirit7** [paulblum/ME33#1]
RLException: [room_evac.launch] is neither a launch file in package [room_evac_gazebo] nor is [room_evac_gazebo] a launch file name
The traceback for the exception was written to the log file

**Comment by paulblum** [comment]
Hello, thanks for submitting this issue.

The repository was recently updated and the readme is currently out of date (sorry! 😬)-- try the following command instead:

`roslaunch gazebo_sim empty_room.launch`

Also, the new script for controlling the jetbot from Python is `ME33/scripts/python_gazebo.py`, the available functions are pretty well documented.

Please let me know how this works for you or if you're having any other issues!

**Comment by noblespirit7** [comment]
> Hello, thanks for submitting this issue.
> 
> The repository was recently updated and the readme is currently out of date (sorry! grimacing)-- try the following command instead:
> 
> `roslaunch gazebo_sim empty_room.launch`
> 
> Also, the new script for controlling the jetbot from Python is `ME33/scripts/python_gazebo.py`, the available functions are pretty well documented.
> 
> Please let me know how this works for you or if you're having any other issues!

**Comment by noblespirit7** [comment]
Resource not found: gazebo_ros
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/ubuntu/ME33/src
ROS path [2]=/home/ubuntu/catkin_ws/src
ROS path [3]=/opt/ros/melodic/share
The traceback for the exception was written to the log file

**Comment by noblespirit7** [comment]
thanks !
